language: c
sudo: required

install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh
  - bash -ex .travis-ocaml.sh
  - make init
  - if [[ -v TESTJSJSREF ]]; then make test_init; fi
  - eval `opam config env`

script:
  - make
  - if [[ -v TESTJSJSREF ]]; then make test; fi

env:
  global:
    - OCAML_VERSION=4.03
    - OPAMYES=true

matrix:
  include:
    - os: linux
      env: TESTJSJSREF=true
    - os: linux
      env: DEPLOY=true
    - os: osx

deploy:
  skip_cleanup: true
  provider: script
  script: make publish-github
  on:
    condition: $DEPLOY = true
    all_branches: true

