language: node_js
sudo: required
dist: trusty

# a reasonably recent node is required to run tests, it depends on
node_js:
  - "4"

env:
  global:
    - OCAML_VERSION=4.03
    - OPAMYES=true
    - UBUNTU_TRUSTY=1

matrix:
  include:
    - os: linux
      env: TESTJSJSREF=true
    - os: linux
      env: DEPLOY=true
    - os: osx


install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh
  - bash -ex .travis-ocaml.sh
  - make init
  - if [[ -v TESTJSJSREF ]]; then make test_init; fi
  - eval `opam config env`

script:
  - make
  - if [[ -v TESTJSJSREF ]]; then make test; fi

deploy:
  skip_cleanup: true
  provider: script
  script: make publish-github
  on:
    condition: $DEPLOY = true
    all_branches: true

